<a href="https://colab.research.google.com/github/D-Ranaprathap/20221CCS0021/blob/main/DATA_WRANGLING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv('/content/drive/MyDrive/train.csv')
print(df)

     survived  pclass                                               name  \
0           0       3                            Braund, Mr. Owen Harris
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2           1       3                             Heikkinen, Miss. Laina
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4           0       3                           Allen, Mr. William Henry
..        ...     ...                                                ...
886         0       2                              Montvila, Rev. Juozas
887         1       1                       Graham, Miss. Margaret Edith
888         0       3           Johnston, Miss. Catherine Helen "Carrie"
889         1       1                              Behr, Mr. Karl Howell
890         0       3                                Dooley, Mr. Patrick

        sex   age  sibsp  parch            ticket     fare cabin embarked
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S
1    female  38.0      1      0          PC 17599  71.2833   C85        C
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3    female  35.0      1      0            113803  53.1000  C123        S
4      male  35.0      0      0            373450   8.0500   NaN        S
..      ...   ...    ...    ...               ...      ...   ...      ...
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q

[891 rows x 11 columns]

In [9]:
df.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df.dtypes

survived      int64
pclass        int64
name         object
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
embarked     object
dtype: object

In [16]:
df.describe()

       survived    pclass        age     sibsp  parch       fare
count  8.000000  8.000000   8.000000  8.000000    8.0   8.000000
mean   0.500000  2.000000  29.500000  0.500000    0.0  29.070825
std    0.534522  1.069045   6.480741  0.534522    0.0  27.843863
min    0.000000  1.000000  22.000000  0.000000    0.0   7.250000
25%    0.000000  1.000000  25.000000  0.000000    0.0   7.625000
50%    0.500000  2.000000  29.000000  0.500000    0.0  18.875000
75%    1.000000  3.000000  33.500000  1.000000    0.0  40.320825
max    1.000000  3.000000  38.000000  1.000000    0.0  71.283300

In [10]:
null_values = df.isnull().sum()
print(null_values)

survived      0
pclass        0
name          0
sex           0
age         177
sibsp         0
parch         0
ticket        0
fare          0
cabin       687
embarked      2
dtype: int64

In [11]:
age_mean = df['age'].mean()
df['age'].fillna(age_mean, inplace=True)
df.to_csv('train_filled.csv', index=False)
print("Null values filled with mean of age and saved to train_filled.csv")
print(age_mean)

Null values filled with mean of age and saved to train_filled.csv
29.69911764705882

In [12]:
df.drop(columns=['cabin'], inplace=True)
df.to_csv('train_without_cabin.csv', index=False)
print("Column 'cabin' dropped and saved to train_without_cabin.csv")

Column 'cabin' dropped and saved to train_without_cabin.csv

In [24]:
pass_over_30=df[df['age']>30][['name','age']]
print(pass_over_30)

                                                name   age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
5                                Dooley, Mr. Patrick  32.0
7                                Dooley, Mr. Patrick  32.0

In [18]:
first_two_rows = df.iloc[:2]
last_two_rows = df.iloc[-2:]
merged_rows = pd.concat([first_two_rows, last_two_rows])
print(merged_rows)

   survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
6         1       1                              Behr, Mr. Karl Howell
7         0       3                                Dooley, Mr. Patrick

      sex   age  sibsp  parch     ticket     fare embarked
0    male  22.0      1      0  A/5 21171   7.2500        S
1  female  38.0      1      0   PC 17599  71.2833        C
6    male  26.0      0      0     111369  30.0000        C
7    male  32.0      0      0     370376   7.7500        Q